spring.application.name=SpringBatchMultipleJobsConfiguration
spring.application.version=1.0.0
spring.application.author=BabinKuk

file.input=coffee-list.csv

spring.batch.jdbc.initialize-schema=always